"""Technical analysis models for quantitative analysis."""

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field, field_validator, model_validator

from finwiz.schemas.quantitative.enums import SignalType


class TechnicalSignal(BaseModel):
    """Represents a technical analysis signal."""

    signal_type: SignalType = Field(..., description="Type of signal")
    strength: float = Field(..., ge=0, le=1, description="Signal strength (0-1)")
    confidence: float = Field(..., ge=0, le=1, description="Confidence in signal")
    timestamp: datetime = Field(..., description="When signal was generated")
    indicator_name: str = Field(..., description="Name of indicator generating signal")
    price_level: float | None = Field(None, description="Price level associated with signal")


class IndicatorSignal(BaseModel):
    """Individual technical indicator signal (legacy compatibility)."""

    indicator: str = Field(..., description="Indicator name")
    signal: SignalType = Field(..., description="Signal type")
    strength: float = Field(..., ge=0, le=1, description="Signal strength")
    value: float = Field(..., description="Indicator value")
    timestamp: datetime = Field(..., description="Signal timestamp")


class ConfluenceZone(BaseModel):
    """Represents a confluence zone where multiple indicators align."""

    price_level: float = Field(..., description="Price level of confluence")
    support_count: int = Field(..., description="Number of supporting indicators")
    resistance_count: int = Field(..., description="Number of resistance indicators")
    strength: float = Field(..., ge=0, le=1, description="Overall confluence strength")
    indicators: list[str] = Field(..., description="List of contributing indicators")
    zone_type: Literal["support", "resistance", "neutral"] = Field(..., description="Type of confluence zone")

    @field_validator("strength")
    @classmethod
    def validate_strength_range(cls, v: float) -> float:
        """Validate strength is between 0 and 1."""
        if not 0 <= v <= 1:
            raise ValueError("Strength must be between 0 and 1")
        return v


class FibonacciLevels(BaseModel):
    """Fibonacci retracement and extension levels."""

    high_price: float = Field(..., description="High price for Fibonacci calculation")
    low_price: float = Field(..., description="Low price for Fibonacci calculation")

    # Retracement levels
    retracement_23_6: float = Field(..., description="23.6% retracement level")
    retracement_38_2: float = Field(..., description="38.2% retracement level")
    retracement_50_0: float = Field(..., description="50.0% retracement level")
    retracement_61_8: float = Field(..., description="61.8% retracement level")
    retracement_78_6: float = Field(..., description="78.6% retracement level")

    # Extension levels
    extension_127_2: float = Field(..., description="127.2% extension level")
    extension_161_8: float = Field(..., description="161.8% extension level")
    extension_261_8: float = Field(..., description="261.8% extension level")


class SupportResistance(BaseModel):
    """Support and resistance levels analysis."""

    support_levels: list[float] = Field(..., description="Identified support levels")
    resistance_levels: list[float] = Field(..., description="Identified resistance levels")
    current_price: float = Field(..., description="Current price for context")

    # Strength indicators
    support_strength: list[float] = Field(..., description="Strength of each support level (0-1)")
    resistance_strength: list[float] = Field(..., description="Strength of each resistance level (0-1)")

    # Key levels
    key_support: float | None = Field(None, description="Most significant support level")
    key_resistance: float | None = Field(None, description="Most significant resistance level")

    @model_validator(mode="after")
    def validate_strength_lists_length(self) -> "SupportResistance":
        """Validate that strength lists match level lists length."""
        if len(self.support_strength) != len(self.support_levels):
            raise ValueError("Support strength list must match support levels list length")
        if len(self.resistance_strength) != len(self.resistance_levels):
            raise ValueError("Resistance strength list must match resistance levels list length")
        return self


class TechnicalIndicatorValue(BaseModel):
    """Individual technical indicator data point."""

    value: float = Field(..., description="Indicator value")
    signal: SignalType | None = Field(None, description="Signal generated by indicator")
    timestamp: datetime = Field(..., description="Timestamp of the value")


class TechnicalIndicatorSummary(BaseModel):
    """Summary of all technical indicators for a symbol."""

    symbol: str = Field(..., description="Symbol analyzed")
    timestamp: datetime = Field(..., description="Analysis timestamp")

    # Moving averages
    sma_20: float | None = Field(None, description="20-period Simple Moving Average")
    sma_50: float | None = Field(None, description="50-period Simple Moving Average")
    sma_200: float | None = Field(None, description="200-period Simple Moving Average")
    ema_12: float | None = Field(None, description="12-period Exponential Moving Average")
    ema_26: float | None = Field(None, description="26-period Exponential Moving Average")

    # Momentum indicators
    rsi: float | None = Field(None, description="Relative Strength Index")
    macd: float | None = Field(None, description="MACD line")
    macd_signal: float | None = Field(None, description="MACD signal line")
    macd_histogram: float | None = Field(None, description="MACD histogram")

    # Volatility indicators
    bollinger_upper: float | None = Field(None, description="Bollinger Band upper")
    bollinger_middle: float | None = Field(None, description="Bollinger Band middle")
    bollinger_lower: float | None = Field(None, description="Bollinger Band lower")
    atr: float | None = Field(None, description="Average True Range")


class TechnicalAnalysisResult(BaseModel):
    """Comprehensive technical analysis result."""

    symbol: str = Field(..., description="Symbol analyzed")
    timestamp: datetime = Field(..., description="Analysis timestamp")
    current_price: float = Field(..., description="Current price")

    # Overall assessment
    overall_signal: SignalType = Field(..., description="Overall technical signal")
    signal_strength: float = Field(..., ge=0, le=1, description="Overall signal strength")
    confidence: float = Field(..., ge=0, le=1, description="Confidence in analysis")

    # Component analysis
    indicators: TechnicalIndicatorSummary = Field(..., description="Technical indicators summary")
    signals: list[TechnicalSignal] = Field(..., description="Individual technical signals")
    confluence_zones: list[ConfluenceZone] = Field(..., description="Price confluence zones")
    support_resistance: SupportResistance = Field(..., description="Support and resistance analysis")
    fibonacci: FibonacciLevels | None = Field(None, description="Fibonacci analysis")

    # Market structure
    trend_direction: Literal["up", "down", "sideways"] = Field(..., description="Overall trend direction")
    trend_strength: float = Field(..., ge=0, le=1, description="Trend strength")

    # Risk levels
    stop_loss_suggestion: float | None = Field(None, description="Suggested stop loss level")
    take_profit_suggestion: float | None = Field(None, description="Suggested take profit level")
