"""
A+ Opportunity Data Extractor for Discovery Crew Integration.

This module extracts A+ investment opportunities from discovery crew outputs
and structures them for integration into the reporting system.
"""

import logging
import re
from datetime import datetime
from pathlib import Path

from ..schemas.integration import APlusOpportunityCollection


class APlusDataExtractor:
    """
    Extracts and processes A+ opportunity data from discovery crew outputs.

    This class parses markdown files generated by the discovery crew to extract
    structured A+ opportunity data including allocation recommendations and
    replacement notes.
    """

    def __init__(self, output_dir: Path = Path("output")) -> None:
        """
        Initialize the A+ data extractor.

        Args:
            output_dir: Base output directory containing crew outputs

        """
        self.output_dir = output_dir
        self.discovery_dir = output_dir / "discovery"
        self.logger = logging.getLogger(__name__)

        self.logger.info(
            "APlusDataExtractor initialized", extra={"output_dir": str(output_dir), "discovery_dir": str(self.discovery_dir)}
        )

    def extract_aplus_opportunities(self) -> APlusOpportunityCollection | None:
        """
        Extract A+ opportunities from all discovery crew files.

        Returns:
            APlusOpportunityCollection with extracted opportunities, or None if extraction fails

        """
        try:
            # Check if discovery directory exists
            if not self.discovery_dir.exists():
                self.logger.warning(f"Discovery directory not found: {self.discovery_dir}")
                return None

            # Extract opportunities from each asset class
            stock_opportunities = self._extract_stock_opportunities()
            etf_opportunities = self._extract_etf_opportunities()
            crypto_opportunities = self._extract_crypto_opportunities()

            # Generate discovery summary
            discovery_summary = self._generate_discovery_summary(stock_opportunities, etf_opportunities, crypto_opportunities)

            # Calculate confidence score based on data availability
            confidence_score = self._calculate_confidence_score(stock_opportunities, etf_opportunities, crypto_opportunities)

            # Extract allocation recommendations and replacement notes
            allocation_recommendations = self._extract_allocation_recommendations(
                stock_opportunities, etf_opportunities, crypto_opportunities
            )
            replacement_notes = self._extract_replacement_notes(stock_opportunities, etf_opportunities, crypto_opportunities)

            collection = APlusOpportunityCollection(
                etf_opportunities=[opp["symbol"] for opp in etf_opportunities],
                stock_opportunities=[opp["symbol"] for opp in stock_opportunities],
                crypto_opportunities=[opp["symbol"] for opp in crypto_opportunities],
                discovery_summary=discovery_summary,
                confidence_score=confidence_score,
                validation_timestamp=datetime.now(),
                allocation_recommendations=allocation_recommendations,
                replacement_notes=replacement_notes,
            )

            self.logger.info(
                "A+ opportunities extracted successfully",
                extra={
                    "stock_count": len(stock_opportunities),
                    "etf_count": len(etf_opportunities),
                    "crypto_count": len(crypto_opportunities),
                    "confidence_score": confidence_score,
                },
            )

            return collection

        except Exception as e:
            self.logger.error(f"Failed to extract A+ opportunities: {str(e)}", exc_info=True)
            return None

    def _extract_stock_opportunities(self) -> list[dict[str, any]]:
        """Extract A+ stock opportunities from a_plus_stocks.md file."""
        stock_file = self.discovery_dir / "a_plus_stocks.md"

        if not stock_file.exists():
            self.logger.warning(f"Stock A+ file not found: {stock_file}")
            return []

        try:
            content = stock_file.read_text(encoding="utf-8")
            opportunities = []

            # Pattern to match stock entries with A+ grades
            # Matches: "1) NVIDIA (NVDA) — A+ grade" or "2) Broadcom (AVGO) — A+ grade"
            stock_pattern = r"(\d+)\)\s+([^(]+)\s*\(([^)]+)\)\s*—\s*(A\+|A)\s+grade"

            matches = re.finditer(stock_pattern, content, re.IGNORECASE | re.MULTILINE)

            for match in matches:
                rank = int(match.group(1))
                company_name = match.group(2).strip()
                symbol = match.group(3).strip()
                grade = match.group(4).strip()

                # Extract additional details for this stock
                stock_details = self._extract_stock_details(content, symbol, company_name)

                opportunity = {
                    "symbol": symbol,
                    "company_name": company_name,
                    "grade": grade,
                    "rank": rank,
                    "allocation_recommendation": stock_details.get("allocation", ""),
                    "replacement_note": stock_details.get("replacement", ""),
                    "risk_score": stock_details.get("risk_score", 5),
                    "confidence": stock_details.get("confidence", 0.8),
                }

                opportunities.append(opportunity)

            # Sort by rank
            opportunities.sort(key=lambda x: x["rank"])

            self.logger.info(f"Extracted {len(opportunities)} stock A+ opportunities")
            return opportunities

        except Exception as e:
            self.logger.error(f"Failed to extract stock opportunities: {str(e)}", exc_info=True)
            return []

    def _extract_etf_opportunities(self) -> list[dict[str, any]]:
        """Extract A+ ETF opportunities from a_plus_etfs.md file."""
        etf_file = self.discovery_dir / "a_plus_etfs.md"

        if not etf_file.exists():
            self.logger.warning(f"ETF A+ file not found: {etf_file}")
            return []

        try:
            content = etf_file.read_text(encoding="utf-8")
            opportunities = []

            # Pattern to match ETF entries with A+ grades
            # Matches: "1) VWCE – Vanguard FTSE All-World UCITS ETF (Acc)"
            etf_pattern = r"(\d+)\)\s+([A-Z0-9]+)\s*[–-]\s*([^(]+)(?:\([^)]*\))?"

            matches = re.finditer(etf_pattern, content, re.MULTILINE)

            for match in matches:
                rank = int(match.group(1))
                symbol = match.group(2).strip()
                fund_name = match.group(3).strip()

                # Extract grade from the content section for this ETF
                grade = self._extract_etf_grade(content, symbol)

                # Only include A+ and A grade ETFs
                if grade in ["A+", "A"]:
                    # Extract additional details for this ETF
                    etf_details = self._extract_etf_details(content, symbol, fund_name)

                    opportunity = {
                        "symbol": symbol,
                        "fund_name": fund_name,
                        "grade": grade,
                        "rank": rank,
                        "allocation_recommendation": etf_details.get("allocation", ""),
                        "replacement_note": etf_details.get("replacement", ""),
                        "ter": etf_details.get("ter", 0.0),
                        "aum": etf_details.get("aum", ""),
                        "confidence": etf_details.get("confidence", 0.9),
                    }

                    opportunities.append(opportunity)

            # Sort by rank
            opportunities.sort(key=lambda x: x["rank"])

            self.logger.info(f"Extracted {len(opportunities)} ETF A+ opportunities")
            return opportunities

        except Exception as e:
            self.logger.error(f"Failed to extract ETF opportunities: {str(e)}", exc_info=True)
            return []

    def _extract_crypto_opportunities(self) -> list[dict[str, any]]:
        """Extract A+ crypto opportunities from a_plus_crypto.md file."""
        crypto_file = self.discovery_dir / "a_plus_crypto.md"

        if not crypto_file.exists():
            self.logger.warning(f"Crypto A+ file not found: {crypto_file}")
            return []

        try:
            content = crypto_file.read_text(encoding="utf-8")
            opportunities = []

            # Pattern to match crypto entries with A+ grades
            # Matches: "1) Bitcoin (BTC-USD)" or "2) Ethereum (ETH-USD)"
            crypto_pattern = r"(\d+)\)\s+([^(]+)\s*\(([^)]+)\)"

            matches = re.finditer(crypto_pattern, content, re.MULTILINE)

            for match in matches:
                rank = int(match.group(1))
                crypto_name = match.group(2).strip()
                symbol = match.group(3).strip()

                # Extract grade from the content section for this crypto
                grade = self._extract_crypto_grade(content, symbol, crypto_name)

                # Only include A+ and A grade cryptos
                if grade in ["A+", "A", "A-"]:
                    # Extract additional details for this crypto
                    crypto_details = self._extract_crypto_details(content, symbol, crypto_name)

                    opportunity = {
                        "symbol": symbol.replace("-USD", ""),  # Clean symbol
                        "crypto_name": crypto_name,
                        "grade": grade,
                        "rank": rank,
                        "allocation_recommendation": crypto_details.get("allocation", ""),
                        "replacement_note": crypto_details.get("replacement", ""),
                        "risk_score": crypto_details.get("risk_score", 7),
                        "confidence": crypto_details.get("confidence", 0.8),
                    }

                    opportunities.append(opportunity)

            # Sort by rank
            opportunities.sort(key=lambda x: x["rank"])

            self.logger.info(f"Extracted {len(opportunities)} crypto A+ opportunities")
            return opportunities

        except Exception as e:
            self.logger.error(f"Failed to extract crypto opportunities: {str(e)}", exc_info=True)
            return []

    def _extract_stock_details(self, content: str, symbol: str, company_name: str) -> dict[str, any]:
        """Extract detailed information for a specific stock."""
        details = {}

        try:
            # Find the section for this stock
            section_pattern = rf"{re.escape(company_name)}\s*\({re.escape(symbol)}\).*?(?=\d+\)|$)"
            section_match = re.search(section_pattern, content, re.DOTALL | re.IGNORECASE)

            if section_match:
                section_content = section_match.group(0)

                # Extract allocation recommendation
                allocation_match = re.search(r"Optimal allocation:\s*([^.]+)", section_content, re.IGNORECASE)
                if allocation_match:
                    details["allocation"] = allocation_match.group(1).strip()

                # Extract replacement/compatibility info
                replacement_match = re.search(r"Compatibility:\s*([^.]+)", section_content, re.IGNORECASE)
                if replacement_match:
                    details["replacement"] = replacement_match.group(1).strip()

                # Extract confidence from A+ score (multiple patterns)
                score_patterns = [r"A\+\s+Tool\s+score:\s*([\d.]+)", r"A\+\s+score:\s*([\d.]+)", r"score:\s*([\d.]+)"]

                for pattern in score_patterns:
                    score_match = re.search(pattern, section_content, re.IGNORECASE)
                    if score_match:
                        score = float(score_match.group(1))
                        details["confidence"] = min(score, 1.0)  # Ensure it's between 0 and 1
                        break

                # Default confidence if not found
                if "confidence" not in details:
                    details["confidence"] = 0.8

                # Estimate risk score from content
                if "high volatility" in section_content.lower() or "high beta" in section_content.lower():
                    details["risk_score"] = 8
                elif "moderate" in section_content.lower():
                    details["risk_score"] = 6
                else:
                    details["risk_score"] = 5

        except Exception as e:
            self.logger.warning(f"Failed to extract details for {symbol}: {str(e)}")

        return details

    def _extract_etf_grade(self, content: str, symbol: str) -> str:
        """Extract the grade for a specific ETF."""
        try:
            # Look for grade in the ETF section
            grade_pattern = rf"{re.escape(symbol)}.*?Grade:\s*(A\+|A|A-)"
            grade_match = re.search(grade_pattern, content, re.IGNORECASE | re.DOTALL)

            if grade_match:
                return grade_match.group(1)

            # Alternative pattern: "A+ Score/Grade: 0.962 (A+)"
            alt_pattern = rf"{re.escape(symbol)}.*?Score/Grade:.*?\((A\+|A|A-)\)"
            alt_match = re.search(alt_pattern, content, re.IGNORECASE | re.DOTALL)

            if alt_match:
                return alt_match.group(1)

        except Exception as e:
            self.logger.warning(f"Failed to extract grade for ETF {symbol}: {str(e)}")

        return "A"  # Default grade

    def _extract_etf_details(self, content: str, symbol: str, fund_name: str) -> dict[str, any]:
        """Extract detailed information for a specific ETF."""
        details = {}

        try:
            # Find the section for this ETF
            section_pattern = rf"{re.escape(symbol)}.*?(?=\d+\)|$)"
            section_match = re.search(section_pattern, content, re.DOTALL | re.IGNORECASE)

            if section_match:
                section_content = section_match.group(0)

                # Extract TER (Total Expense Ratio) - multiple patterns
                ter_patterns = [r"TER\s*([\d.]+)%", r"Cost:\s*TER\s*([\d.]+)%"]

                for pattern in ter_patterns:
                    ter_match = re.search(pattern, section_content, re.IGNORECASE)
                    if ter_match:
                        details["ter"] = float(ter_match.group(1))
                        break

                # Extract AUM
                aum_match = re.search(r"AUM\s*[~$]*([^;]+)", section_content, re.IGNORECASE)
                if aum_match:
                    details["aum"] = aum_match.group(1).strip()

                # Extract replacement notes
                replacement_match = re.search(r"Replacement.*?:\s*([^.]+)", section_content, re.IGNORECASE)
                if replacement_match:
                    details["replacement"] = replacement_match.group(1).strip()

                # Extract use case as allocation recommendation
                use_case_match = re.search(r"Use Case:\s*([^.]+)", section_content, re.IGNORECASE)
                if use_case_match:
                    details["allocation"] = use_case_match.group(1).strip()

                # High confidence for ETFs due to standardized structure
                details["confidence"] = 0.9

        except Exception as e:
            self.logger.warning(f"Failed to extract details for ETF {symbol}: {str(e)}")

        return details

    def _extract_crypto_grade(self, content: str, symbol: str, crypto_name: str) -> str:
        """Extract the grade for a specific crypto."""
        try:
            # Look for grade in the crypto section
            grade_pattern = rf"{re.escape(crypto_name)}.*?Grade:\s*(A\+|A|A-)"
            grade_match = re.search(grade_pattern, content, re.IGNORECASE | re.DOTALL)

            if grade_match:
                return grade_match.group(1)

            # Alternative pattern: "Composite A+ Score: 0.98 (Grade: A+)"
            alt_pattern = rf"{re.escape(crypto_name)}.*?Grade:\s*(A\+|A|A-)\)"
            alt_match = re.search(alt_pattern, content, re.IGNORECASE | re.DOTALL)

            if alt_match:
                return alt_match.group(1)

        except Exception as e:
            self.logger.warning(f"Failed to extract grade for crypto {symbol}: {str(e)}")

        return "A"  # Default grade

    def _extract_crypto_details(self, content: str, symbol: str, crypto_name: str) -> dict[str, any]:
        """Extract detailed information for a specific crypto."""
        details = {}

        try:
            # Find the section for this crypto
            section_pattern = rf"{re.escape(crypto_name)}.*?(?=\d+\)|$)"
            section_match = re.search(section_pattern, content, re.DOTALL | re.IGNORECASE)

            if section_match:
                section_content = section_match.group(0)

                # Extract allocation recommendation - multiple patterns
                allocation_patterns = [
                    r"Suggested weight:\s*([^.]+)",
                    r"Allocation recommendation:\s*-\s*Suggested weight:\s*([^.]+)",
                ]

                for pattern in allocation_patterns:
                    allocation_match = re.search(pattern, section_content, re.IGNORECASE)
                    if allocation_match:
                        details["allocation"] = allocation_match.group(1).strip()
                        break

                # Extract replacement strategy
                replacement_match = re.search(r"Rebalancing strategy:\s*([^.]+)", section_content, re.IGNORECASE)
                if replacement_match:
                    details["replacement"] = replacement_match.group(1).strip()

                # Extract confidence from composite score
                score_match = re.search(r"Composite.*?Score:\s*([\d.]+)", section_content, re.IGNORECASE)
                if score_match:
                    score = float(score_match.group(1))
                    details["confidence"] = min(score, 1.0)  # Ensure it's between 0 and 1

                # Crypto risk scores are generally higher
                if "high risk" in section_content.lower() or "medium risk" in section_content.lower():
                    details["risk_score"] = 8
                elif "low risk" in section_content.lower():
                    details["risk_score"] = 6
                else:
                    details["risk_score"] = 7  # Default for crypto

        except Exception as e:
            self.logger.warning(f"Failed to extract details for crypto {symbol}: {str(e)}")

        return details

    def _generate_discovery_summary(self, stocks: list[dict], etfs: list[dict], cryptos: list[dict]) -> str:
        """Generate a summary of the discovery analysis."""
        total_opportunities = len(stocks) + len(etfs) + len(cryptos)

        if total_opportunities == 0:
            return "No A+ opportunities identified in current market conditions."

        summary_parts = []

        if stocks:
            a_plus_stocks = [s for s in stocks if s["grade"] == "A+"]
            summary_parts.append(f"{len(stocks)} stock opportunities identified ({len(a_plus_stocks)} A+ grade)")

        if etfs:
            a_plus_etfs = [e for e in etfs if e["grade"] == "A+"]
            summary_parts.append(f"{len(etfs)} ETF opportunities identified ({len(a_plus_etfs)} A+ grade)")

        if cryptos:
            a_plus_cryptos = [c for c in cryptos if c["grade"] == "A+"]
            summary_parts.append(f"{len(cryptos)} crypto opportunities identified ({len(a_plus_cryptos)} A+ grade)")

        summary = f"Discovery analysis identified {total_opportunities} high-quality investment opportunities: " + ", ".join(
            summary_parts
        )
        summary += (
            ". Opportunities selected based on fundamental analysis, competitive moats, "
            "valuation attractiveness, and portfolio integration potential."
        )

        return summary

    def _calculate_confidence_score(self, stocks: list[dict], etfs: list[dict], cryptos: list[dict]) -> float:
        """Calculate overall confidence score based on data availability and quality."""
        if not any([stocks, etfs, cryptos]):
            return 0.0

        # Base confidence on data availability
        base_confidence = 0.7

        # Boost confidence based on number of opportunities
        total_opportunities = len(stocks) + len(etfs) + len(cryptos)
        if total_opportunities >= 10:
            base_confidence += 0.2
        elif total_opportunities >= 5:
            base_confidence += 0.1

        # Boost confidence based on A+ grades
        a_plus_count = sum(
            [
                len([s for s in stocks if s["grade"] == "A+"]),
                len([e for e in etfs if e["grade"] == "A+"]),
                len([c for c in cryptos if c["grade"] == "A+"]),
            ]
        )

        if a_plus_count >= 5:
            base_confidence += 0.1
        elif a_plus_count >= 2:
            base_confidence += 0.05

        return min(base_confidence, 1.0)

    def _extract_allocation_recommendations(self, stocks: list[dict], etfs: list[dict], cryptos: list[dict]) -> list[dict]:
        """Extract allocation recommendations from all opportunities."""
        recommendations = []

        for stock in stocks:
            if stock.get("allocation_recommendation"):
                recommendations.append(
                    {
                        "asset_type": "stock",
                        "symbol": stock["symbol"],
                        "allocation": stock["allocation_recommendation"],
                        "grade": stock["grade"],
                        "rank": stock["rank"],
                    }
                )

        for etf in etfs:
            if etf.get("allocation_recommendation"):
                recommendations.append(
                    {
                        "asset_type": "etf",
                        "symbol": etf["symbol"],
                        "allocation": etf["allocation_recommendation"],
                        "grade": etf["grade"],
                        "rank": etf["rank"],
                    }
                )

        for crypto in cryptos:
            if crypto.get("allocation_recommendation"):
                recommendations.append(
                    {
                        "asset_type": "crypto",
                        "symbol": crypto["symbol"],
                        "allocation": crypto["allocation_recommendation"],
                        "grade": crypto["grade"],
                        "rank": crypto["rank"],
                    }
                )

        return recommendations

    def _extract_replacement_notes(self, stocks: list[dict], etfs: list[dict], cryptos: list[dict]) -> list[str]:
        """Extract replacement notes from all opportunities."""
        notes = []

        for stock in stocks:
            if stock.get("replacement_note"):
                notes.append(f"{stock['symbol']}: {stock['replacement_note']}")

        for etf in etfs:
            if etf.get("replacement_note"):
                notes.append(f"{etf['symbol']}: {etf['replacement_note']}")

        for crypto in cryptos:
            if crypto.get("replacement_note"):
                notes.append(f"{crypto['symbol']}: {crypto['replacement_note']}")

        return notes

    def validate_aplus_opportunities(self, collection: APlusOpportunityCollection) -> tuple[bool, list[str]]:
        """
        Validate A+ opportunities collection for completeness and quality.

        Args:
            collection: The A+ opportunities collection to validate

        Returns:
            Tuple of (is_valid, list_of_validation_errors)

        """
        errors = []

        try:
            # Check if we have any opportunities
            total_opportunities = (
                len(collection.etf_opportunities) + len(collection.stock_opportunities) + len(collection.crypto_opportunities)
            )

            if total_opportunities == 0:
                errors.append("No A+ opportunities found in any asset class")

            # Check confidence score
            if collection.confidence_score < 0.5:
                errors.append(f"Low confidence score: {collection.confidence_score}")

            # Check discovery summary
            if len(collection.discovery_summary) < 50:
                errors.append("Discovery summary is too brief")

            # Check allocation recommendations
            if not collection.allocation_recommendations:
                errors.append("No allocation recommendations provided")

            # Check for duplicate symbols
            all_symbols = collection.stock_opportunities + collection.etf_opportunities + collection.crypto_opportunities

            if len(all_symbols) != len(set(all_symbols)):
                errors.append("Duplicate symbols found in opportunities")

            is_valid = len(errors) == 0

            self.logger.info(
                "A+ opportunities validation completed",
                extra={"is_valid": is_valid, "error_count": len(errors), "total_opportunities": total_opportunities},
            )

            return is_valid, errors

        except Exception as e:
            self.logger.error(f"A+ opportunities validation failed: {str(e)}", exc_info=True)
            return False, [f"Validation error: {str(e)}"]
