"""
A+ Opportunity Data Extractor for Discovery Crew Integration.

This module extracts A+ investment opportunities from discovery crew outputs
and structures them for integration into the reporting system.
"""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any

from finwiz.schemas.integration import APlusOpportunityCollection


class APlusDataExtractor:
    """
    Extracts and processes A+ opportunity data from discovery crew outputs.

    This class parses markdown files generated by the discovery crew to extract
    structured A+ opportunity data including allocation recommendations and
    replacement notes.
    """

    def __init__(self, output_dir: Path = Path("output")) -> None:
        """
        Initialize the A+ data extractor.

        Args:
            output_dir: Base output directory containing crew outputs

        """
        self.output_dir = output_dir
        self.discovery_dir = output_dir / "discovery"
        self.logger = logging.getLogger(__name__)

        self.logger.info(
            "APlusDataExtractor initialized", extra={"output_dir": str(output_dir), "discovery_dir": str(self.discovery_dir)}
        )

    def extract_aplus_opportunities(self) -> APlusOpportunityCollection | None:
        """
        Extract A+ opportunities from all discovery crew files.

        Returns:
            APlusOpportunityCollection with extracted opportunities, or None if extraction fails

        """
        try:
            # Check if discovery directory exists
            if not self.discovery_dir.exists():
                self.logger.warning(f"Discovery directory not found: {self.discovery_dir}")
                return None

            # Extract opportunities from each asset class
            stock_opportunities = self._extract_stock_opportunities()
            etf_opportunities = self._extract_etf_opportunities()
            crypto_opportunities = self._extract_crypto_opportunities()

            # Generate discovery summary
            discovery_summary = self._generate_discovery_summary(stock_opportunities, etf_opportunities, crypto_opportunities)

            # Calculate confidence score based on data availability
            confidence_score = self._calculate_confidence_score(stock_opportunities, etf_opportunities, crypto_opportunities)

            # Extract allocation recommendations and replacement notes
            allocation_recommendations = self._extract_allocation_recommendations(
                stock_opportunities, etf_opportunities, crypto_opportunities
            )
            replacement_notes = self._extract_replacement_notes(stock_opportunities, etf_opportunities, crypto_opportunities)

            # Convert dict opportunities to APlusOpportunity objects
            from finwiz.schemas.integration_models import APlusOpportunity

            etf_opps = [APlusOpportunity(**opp) for opp in etf_opportunities]
            stock_opps = [APlusOpportunity(**opp) for opp in stock_opportunities]
            crypto_opps = [APlusOpportunity(**opp) for opp in crypto_opportunities]

            # Extract market context and backtesting metrics
            market_context = self._extract_market_context()
            backtesting_metrics = self._extract_backtesting_metrics()

            collection = APlusOpportunityCollection(
                etf_opportunities=etf_opps,
                stock_opportunities=stock_opps,
                crypto_opportunities=crypto_opps,
                discovery_summary=discovery_summary,
                confidence_score=confidence_score,
                validation_timestamp=datetime.now(),
                allocation_recommendations=allocation_recommendations,
                replacement_notes=replacement_notes,
                market_context=market_context,
                backtesting_metrics=backtesting_metrics,
            )

            self.logger.info(
                "A+ opportunities extracted successfully",
                extra={
                    "stock_count": len(stock_opportunities),
                    "etf_count": len(etf_opportunities),
                    "crypto_count": len(crypto_opportunities),
                    "confidence_score": confidence_score,
                },
            )

            return collection

        except Exception as e:
            self.logger.error(f"Failed to extract A+ opportunities: {str(e)}", exc_info=True)
            return None

    def _extract_stock_opportunities(self) -> list[dict[str, any]]:
        """Extract A+ stock opportunities from a_plus_stocks.json file."""
        stock_file = self.discovery_dir / "a_plus_stocks.json"

        if not stock_file.exists():
            self.logger.warning(f"Stock A+ file not found: {stock_file}")
            return []

        try:
            content = stock_file.read_text(encoding="utf-8")
            data = json.loads(content)
            opportunities = []

            # Extract from a_plus_candidates array
            candidates = data.get("a_plus_candidates", [])

            for idx, item in enumerate(candidates):
                candidate = item.get("candidate", {})

                # Only include A+ and A grades
                grade = candidate.get("grade", "")
                if grade not in ["A+", "A"]:
                    continue

                symbol = candidate.get("symbol", "")
                company_name = candidate.get("name", "")
                composite_score = item.get("composite_score", 0.85)  # Extract from item
                confidence = item.get("confidence_level", 0.8)

                # Extract risk assessment
                risk_assessment = candidate.get("risk_assessment") or {}
                risk_score = risk_assessment.get("score", 5.0)

                # Extract rationale as list
                rationale = item.get("rationale", [])
                if isinstance(rationale, str):
                    rationale = [rationale]  # Convert string to list

                # Extract key metrics
                key_metrics = item.get("key_metrics", {})

                # Return dict matching APlusOpportunity schema
                opportunity = {
                    "symbol": symbol,
                    "name": company_name,  # Changed from company_name to name
                    "grade": grade,
                    "composite_score": composite_score,  # Added required field
                    "confidence": confidence,
                    "risk_score": risk_score,
                    "allocation_recommendation": " ".join(rationale[:2]) if rationale else "",
                    "replacement_note": candidate.get("recommended_action", ""),
                    "rationale": rationale,  # Added as list
                    "key_metrics": key_metrics,  # Added as dict
                }

                opportunities.append(opportunity)

            self.logger.info(f"Extracted {len(opportunities)} stock A+ opportunities")
            return opportunities

        except Exception as e:
            self.logger.error(f"Failed to extract stock opportunities: {str(e)}", exc_info=True)
            return []

    def _extract_etf_opportunities(self) -> list[dict[str, any]]:
        """Extract A+ ETF opportunities from a_plus_etfs.json file."""
        etf_file = self.discovery_dir / "a_plus_etfs.json"

        if not etf_file.exists():
            self.logger.warning(f"ETF A+ file not found: {etf_file}")
            return []

        try:
            content = etf_file.read_text(encoding="utf-8")
            data = json.loads(content)
            opportunities = []

            # Extract from a_plus_candidates array
            candidates = data.get("a_plus_candidates", [])

            for idx, item in enumerate(candidates):
                candidate = item.get("candidate", {})

                # Only include A+ and A grades
                grade = candidate.get("grade", "")
                if grade not in ["A+", "A"]:
                    continue

                symbol = candidate.get("symbol", "")
                fund_name = candidate.get("name", "")
                composite_score = item.get("composite_score", 0.85)  # Extract from item
                confidence = item.get("confidence_level", 0.9)

                # Extract key metrics
                key_metrics = item.get("key_metrics", {})
                ter = key_metrics.get("ter", 0.0)
                aum = key_metrics.get("aum_usd", 0)

                # Format AUM for display
                if aum >= 1e9:
                    aum_str = f"${aum / 1e9:.1f}B"
                elif aum >= 1e6:
                    aum_str = f"${aum / 1e6:.1f}M"
                else:
                    aum_str = f"${aum:,.0f}"

                # Add formatted AUM to key_metrics
                key_metrics["aum_formatted"] = aum_str

                # Extract rationale as list
                rationale = item.get("rationale", [])
                if isinstance(rationale, str):
                    rationale = [rationale]

                # Extract risk assessment
                risk_assessment = candidate.get("risk_assessment") or {}
                risk_score = risk_assessment.get("score", 3.0)

                # Return dict matching APlusOpportunity schema
                opportunity = {
                    "symbol": symbol,
                    "name": fund_name,  # Changed from fund_name to name
                    "grade": grade,
                    "composite_score": composite_score,  # Added required field
                    "confidence": confidence,
                    "risk_score": risk_score,
                    "allocation_recommendation": " ".join(rationale[:2]) if rationale else "",
                    "replacement_note": candidate.get("recommended_action", ""),
                    "rationale": rationale,  # Added as list
                    "key_metrics": key_metrics,  # Added as dict (includes ter, aum, aum_formatted)
                }

                opportunities.append(opportunity)

            self.logger.info(f"Extracted {len(opportunities)} ETF A+ opportunities")
            return opportunities

        except Exception as e:
            self.logger.error(f"Failed to extract ETF opportunities: {str(e)}", exc_info=True)
            return []

    def _extract_crypto_opportunities(self) -> list[dict[str, any]]:
        """Extract A+ crypto opportunities from a_plus_crypto.json file."""
        crypto_file = self.discovery_dir / "a_plus_crypto.json"

        if not crypto_file.exists():
            self.logger.warning(f"Crypto A+ file not found: {crypto_file}")
            return []

        try:
            content = crypto_file.read_text(encoding="utf-8")
            data = json.loads(content)
            opportunities = []

            # Extract from a_plus_candidates array
            candidates = data.get("a_plus_candidates", [])

            for idx, item in enumerate(candidates):
                candidate = item.get("candidate", {})

                # Only include A+ and A grades
                grade = candidate.get("grade", "")
                if grade not in ["A+", "A"]:
                    continue

                symbol = candidate.get("symbol", "")
                crypto_name = candidate.get("name", "")
                composite_score = item.get("composite_score", 0.80)  # Extract from item
                confidence = item.get("confidence_level", 0.85)

                # Extract key metrics
                key_metrics = item.get("key_metrics", {})

                # Extract rationale as list
                rationale = item.get("rationale", [])
                if isinstance(rationale, str):
                    rationale = [rationale]

                # Extract risk assessment
                risk_assessment = candidate.get("risk_assessment") or {}
                risk_score = risk_assessment.get("score", 6.0)  # Crypto typically higher risk

                # Return dict matching APlusOpportunity schema
                opportunity = {
                    "symbol": symbol.replace("-USD", ""),  # Clean symbol
                    "name": crypto_name,  # Changed from crypto_name to name
                    "grade": grade,
                    "composite_score": composite_score,  # Added required field
                    "confidence": confidence,
                    "risk_score": risk_score,
                    "allocation_recommendation": " ".join(rationale[:2]) if rationale else "",
                    "replacement_note": candidate.get("recommended_action", ""),
                    "rationale": rationale,  # Added as list
                    "key_metrics": key_metrics,  # Added as dict
                }

                opportunities.append(opportunity)

            self.logger.info(f"Extracted {len(opportunities)} crypto A+ opportunities")
            return opportunities

        except Exception as e:
            self.logger.error(f"Failed to extract crypto opportunities: {str(e)}", exc_info=True)
            return []

    def _generate_discovery_summary(self, stocks: list[dict], etfs: list[dict], cryptos: list[dict]) -> str:
        """Generate a summary of the discovery analysis."""
        total_opportunities = len(stocks) + len(etfs) + len(cryptos)

        if total_opportunities == 0:
            return "No A+ opportunities identified in current market conditions."

        summary_parts = []

        if stocks:
            a_plus_stocks = [s for s in stocks if s["grade"] == "A+"]
            summary_parts.append(f"{len(stocks)} stock opportunities identified ({len(a_plus_stocks)} A+ grade)")

        if etfs:
            a_plus_etfs = [e for e in etfs if e["grade"] == "A+"]
            summary_parts.append(f"{len(etfs)} ETF opportunities identified ({len(a_plus_etfs)} A+ grade)")

        if cryptos:
            a_plus_cryptos = [c for c in cryptos if c["grade"] == "A+"]
            summary_parts.append(f"{len(cryptos)} crypto opportunities identified ({len(a_plus_cryptos)} A+ grade)")

        summary = f"Discovery analysis identified {total_opportunities} high-quality investment opportunities: " + ", ".join(
            summary_parts
        )
        summary += (
            ". Opportunities selected based on fundamental analysis, competitive moats, "
            "valuation attractiveness, and portfolio integration potential."
        )

        return summary

    def _calculate_confidence_score(self, stocks: list[dict], etfs: list[dict], cryptos: list[dict]) -> float:
        """Calculate overall confidence score based on data availability and quality."""
        if not any([stocks, etfs, cryptos]):
            return 0.0

        # Base confidence on data availability
        base_confidence = 0.7

        # Boost confidence based on number of opportunities
        total_opportunities = len(stocks) + len(etfs) + len(cryptos)
        if total_opportunities >= 10:
            base_confidence += 0.2
        elif total_opportunities >= 5:
            base_confidence += 0.1

        # Boost confidence based on A+ grades
        a_plus_count = sum(
            [
                len([s for s in stocks if s["grade"] == "A+"]),
                len([e for e in etfs if e["grade"] == "A+"]),
                len([c for c in cryptos if c["grade"] == "A+"]),
            ]
        )

        if a_plus_count >= 5:
            base_confidence += 0.1
        elif a_plus_count >= 2:
            base_confidence += 0.05

        return min(base_confidence, 1.0)

    def _extract_allocation_recommendations(self, stocks: list[dict], etfs: list[dict], cryptos: list[dict]) -> list[dict]:
        """Extract allocation recommendations from all opportunities."""
        recommendations = []

        for idx, stock in enumerate(stocks, start=1):
            if stock.get("allocation_recommendation"):
                recommendations.append(
                    {
                        "asset_type": "stock",
                        "symbol": stock["symbol"],
                        "allocation": stock["allocation_recommendation"],
                        "grade": stock["grade"],
                        "rank": idx,
                    }
                )

        for idx, etf in enumerate(etfs, start=1):
            if etf.get("allocation_recommendation"):
                recommendations.append(
                    {
                        "asset_type": "etf",
                        "symbol": etf["symbol"],
                        "allocation": etf["allocation_recommendation"],
                        "grade": etf["grade"],
                        "rank": idx,
                    }
                )

        for idx, crypto in enumerate(cryptos, start=1):
            if crypto.get("allocation_recommendation"):
                recommendations.append(
                    {
                        "asset_type": "crypto",
                        "symbol": crypto["symbol"],
                        "allocation": crypto["allocation_recommendation"],
                        "grade": crypto["grade"],
                        "rank": idx,
                    }
                )

        return recommendations

    def _extract_replacement_notes(self, stocks: list[dict], etfs: list[dict], cryptos: list[dict]) -> list[str]:
        """Extract replacement notes from all opportunities."""
        notes = []

        for stock in stocks:
            if stock.get("replacement_note"):
                notes.append(f"{stock['symbol']}: {stock['replacement_note']}")

        for etf in etfs:
            if etf.get("replacement_note"):
                notes.append(f"{etf['symbol']}: {etf['replacement_note']}")

        for crypto in cryptos:
            if crypto.get("replacement_note"):
                notes.append(f"{crypto['symbol']}: {crypto['replacement_note']}")

        return notes

    def validate_aplus_opportunities(self, collection: APlusOpportunityCollection) -> tuple[bool, list[str]]:
        """
        Validate A+ opportunities collection for completeness and quality.

        Args:
            collection: The A+ opportunities collection to validate

        Returns:
            Tuple of (is_valid, list_of_validation_errors)

        """
        errors = []

        try:
            # Check if we have any opportunities
            total_opportunities = (
                len(collection.etf_opportunities) + len(collection.stock_opportunities) + len(collection.crypto_opportunities)
            )

            if total_opportunities == 0:
                errors.append("No A+ opportunities found in any asset class")

            # Check confidence score
            if collection.confidence_score < 0.5:
                errors.append(f"Low confidence score: {collection.confidence_score}")

            # Check discovery summary
            if len(collection.discovery_summary) < 50:
                errors.append("Discovery summary is too brief")

            # Check allocation recommendations
            if not collection.allocation_recommendations:
                errors.append("No allocation recommendations provided")

            # Check for duplicate symbols (extract symbols from APlusOpportunity objects)
            all_symbols = (
                [opp.symbol for opp in collection.stock_opportunities]
                + [opp.symbol for opp in collection.etf_opportunities]
                + [opp.symbol for opp in collection.crypto_opportunities]
            )

            if len(all_symbols) != len(set(all_symbols)):
                errors.append("Duplicate symbols found in opportunities")

            is_valid = len(errors) == 0

            self.logger.info(
                "A+ opportunities validation completed",
                extra={"is_valid": is_valid, "error_count": len(errors), "total_opportunities": total_opportunities},
            )

            return is_valid, errors

        except Exception as e:
            self.logger.error(f"A+ opportunities validation failed: {str(e)}", exc_info=True)
            return False, [f"Validation error: {str(e)}"]

    def _extract_market_context(self) -> dict[str, Any] | None:
        """Extract market context from discovery_latest.json."""
        try:
            discovery_file = self.discovery_dir / "discovery_latest.json"
            if not discovery_file.exists():
                return None

            content = discovery_file.read_text(encoding="utf-8")
            data = json.loads(content)

            # Extract market context if available
            market_context = data.get("market_context", {})
            if market_context:
                self.logger.info("Market context extracted from discovery results")
                return market_context

            return None
        except Exception as e:
            self.logger.warning(f"Could not extract market context: {e}")
            return None

    def _extract_backtesting_metrics(self) -> dict[str, Any] | None:
        """Extract backtesting metrics from discovery_latest.json."""
        try:
            discovery_file = self.discovery_dir / "discovery_latest.json"
            if not discovery_file.exists():
                return None

            content = discovery_file.read_text(encoding="utf-8")
            data = json.loads(content)

            # Extract validation results which contain backtesting data
            validation_results = data.get("validation_results", [])
            if validation_results:
                # Aggregate backtesting metrics
                metrics = {
                    "total_candidates_tested": len(validation_results),
                    "candidates_with_backtests": sum(1 for v in validation_results if v.get("backtest_results")),
                    "avg_sharpe_ratio": None,
                    "avg_annual_return": None,
                    "avg_max_drawdown": None,
                }

                # Calculate averages if backtest data exists
                sharpe_ratios = []
                annual_returns = []
                max_drawdowns = []

                for result in validation_results:
                    backtest = result.get("backtest_results", {})
                    if backtest:
                        if "sharpe_ratio" in backtest:
                            sharpe_ratios.append(backtest["sharpe_ratio"])
                        if "annual_return" in backtest:
                            annual_returns.append(backtest["annual_return"])
                        if "max_drawdown" in backtest:
                            max_drawdowns.append(backtest["max_drawdown"])

                if sharpe_ratios:
                    metrics["avg_sharpe_ratio"] = sum(sharpe_ratios) / len(sharpe_ratios)
                if annual_returns:
                    metrics["avg_annual_return"] = sum(annual_returns) / len(annual_returns)
                if max_drawdowns:
                    metrics["avg_max_drawdown"] = sum(max_drawdowns) / len(max_drawdowns)

                self.logger.info(f"Backtesting metrics extracted: {metrics['candidates_with_backtests']} candidates with backtests")
                return metrics

            return None
        except Exception as e:
            self.logger.warning(f"Could not extract backtesting metrics: {e}")
            return None
