"""
A+ Opportunity Data Extractor for Discovery Crew Integration.

This module extracts A+ investment opportunities from discovery crew outputs
and structures them for integration into the reporting system.
"""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any

from finwiz.schemas.integration import APlusOpportunityCollection


class APlusDataExtractor:
    """
    Extracts and processes A+ opportunity data from discovery crew outputs.

    This class parses markdown files generated by the discovery crew to extract
    structured A+ opportunity data including allocation recommendations and
    replacement notes.
    """

    def __init__(self, output_dir: Path = Path("output")) -> None:
        """
        Initialize the A+ data extractor.

        Args:
            output_dir: Base output directory containing crew outputs

        """
        self.output_dir = output_dir
        self.discovery_dir = output_dir / "discovery"
        self.logger = logging.getLogger(__name__)

        self.logger.info("APlusDataExtractor initialized", extra={"output_dir": str(output_dir), "discovery_dir": str(self.discovery_dir)})

    def _clean_json_content(self, content: str) -> str:
        """
        Clean JSON content to fix common formatting issues.

        Fixes:
        - Python-style numeric literals with underscores (e.g., 1_000_000 -> 1000000)
        - Trailing commas in arrays and objects
        - Multiple consecutive commas

        Args:
            content: Raw JSON content string

        Returns:
            Cleaned JSON content string

        """
        import re

        # Remove underscores from numeric literals
        # Match numbers with underscores: 1_000_000, 20_000_000_000, etc.
        content = re.sub(r"(\d)_(\d)", r"\1\2", content)

        # Remove trailing commas before closing brackets/braces
        # Fix: ,] -> ]
        content = re.sub(r",\s*]", "]", content)
        # Fix: ,} -> }
        content = re.sub(r",\s*}", "}", content)

        # Remove multiple consecutive commas
        # Fix: ,, -> ,
        content = re.sub(r",\s*,", ",", content)

        # Remove stray characters after closing braces/brackets
        # Fix: }% -> }, ]% -> ]
        content = re.sub(r"([}\]])\s*[^,\s}\]]+\s*$", r"\1", content, flags=re.MULTILINE)

        # Fix incomplete JSON - add missing closing braces/brackets
        open_braces = content.count("{")
        close_braces = content.count("}")
        open_brackets = content.count("[")
        close_brackets = content.count("]")

        # Add missing closing braces
        if open_braces > close_braces:
            content = content.rstrip() + "\n" + ("}" * (open_braces - close_braces))

        # Add missing closing brackets
        if open_brackets > close_brackets:
            content = content.rstrip() + "\n" + ("]" * (open_brackets - close_brackets))

        return content

    def _load_and_parse_json(self, file_path: Path, asset_type: str) -> list[dict[str, Any]]:
        """
        Load and parse JSON file with comprehensive error handling.

        This helper method consolidates duplicate JSON parsing logic across
        stock, ETF, and crypto extraction methods.

        Args:
            file_path: Path to the JSON file to load
            asset_type: Type of asset for logging (stock, etf, crypto)

        Returns:
            List of candidate dictionaries, or empty list if file missing/invalid

        """
        # Check if file exists
        if not file_path.exists():
            self.logger.warning(f"{asset_type.capitalize()} A+ file not found: {file_path}")
            return []

        try:
            # Read file content
            content = file_path.read_text(encoding="utf-8")

            # Check if file is empty
            if not content or content.strip() == "":
                self.logger.warning(f"{asset_type.capitalize()} A+ file is empty: {file_path}")
                return []

            # Clean JSON content (fix Python-style numeric literals, trailing commas, etc.)
            content = self._clean_json_content(content)

            # Parse JSON
            try:
                data = json.loads(content)
            except json.JSONDecodeError as e:
                # Log the problematic area for debugging
                lines = content.split("\n")
                error_line = e.lineno - 1 if e.lineno <= len(lines) else len(lines) - 1
                context_start = max(0, error_line - 2)
                context_end = min(len(lines), error_line + 3)
                context = "\n".join(f"{i + 1}: {lines[i]}" for i in range(context_start, context_end))
                self.logger.error(f"JSON parsing error in {file_path.name} at line {e.lineno}, column {e.colno}:\n{context}")
                raise

            # Handle different data structures
            # Case 1: data is already a list of candidates
            if isinstance(data, list):
                candidates = data
            # Case 2: data is a dict with "candidates" or "a_plus_candidates" key
            elif isinstance(data, dict):
                candidates = data.get("candidates", data.get("a_plus_candidates", []))
            else:
                self.logger.error(f"Unexpected data type in {file_path.name}: {type(data)}")
                return []

            # Unwrap nested "candidate" objects if present
            # Some data formats have: [{"candidate": {...}, "composite_score": ...}, ...]
            # We need to merge the wrapper fields with the inner candidate object
            unwrapped_candidates = []
            for item in candidates:
                if isinstance(item, dict) and "candidate" in item:
                    # Nested structure - merge wrapper fields with inner candidate
                    inner_candidate = item["candidate"].copy()
                    # Add wrapper-level fields to the candidate (if not already present)
                    for key, value in item.items():
                        if key != "candidate" and key not in inner_candidate:
                            inner_candidate[key] = value
                    unwrapped_candidates.append(inner_candidate)
                else:
                    # Flat structure - use as is
                    unwrapped_candidates.append(item)

            return unwrapped_candidates

        except Exception as e:
            self.logger.error(f"Failed to load {asset_type} opportunities from {file_path}: {str(e)}", exc_info=True)
            return []

    def extract_aplus_opportunities(self) -> APlusOpportunityCollection | None:
        """
        Extract A+ opportunities from all discovery crew files.

        Returns:
            APlusOpportunityCollection with extracted opportunities, or None if extraction fails

        """
        try:
            # Check if discovery directory exists
            if not self.discovery_dir.exists():
                self.logger.warning(f"Discovery directory not found: {self.discovery_dir}")
                return None

            # Extract opportunities from each asset class
            stock_opportunities = self._extract_stock_opportunities()
            etf_opportunities = self._extract_etf_opportunities()
            crypto_opportunities = self._extract_crypto_opportunities()

            # Generate discovery summary
            discovery_summary = self._generate_discovery_summary(stock_opportunities, etf_opportunities, crypto_opportunities)

            # Calculate confidence score based on data availability
            confidence_score = self._calculate_confidence_score(stock_opportunities, etf_opportunities, crypto_opportunities)

            # Extract allocation recommendations and replacement notes
            allocation_recommendations = self._extract_allocation_recommendations(stock_opportunities, etf_opportunities, crypto_opportunities)
            replacement_notes = self._extract_replacement_notes(stock_opportunities, etf_opportunities, crypto_opportunities)

            # Convert dict opportunities to APlusOpportunity objects
            from finwiz.schemas.integration_models import APlusOpportunity

            etf_opps = [APlusOpportunity(**opp) for opp in etf_opportunities]
            stock_opps = [APlusOpportunity(**opp) for opp in stock_opportunities]
            crypto_opps = [APlusOpportunity(**opp) for opp in crypto_opportunities]

            # Extract market context and backtesting metrics
            market_context = self._extract_market_context()
            backtesting_metrics = self._extract_backtesting_metrics()

            collection = APlusOpportunityCollection(
                etf_opportunities=etf_opps,
                stock_opportunities=stock_opps,
                crypto_opportunities=crypto_opps,
                discovery_summary=discovery_summary,
                confidence_score=confidence_score,
                validation_timestamp=datetime.now(),
                allocation_recommendations=allocation_recommendations,
                replacement_notes=replacement_notes,
                market_context=market_context,
                backtesting_metrics=backtesting_metrics,
            )

            self.logger.info(
                "A+ opportunities extracted successfully",
                extra={
                    "stock_count": len(stock_opportunities),
                    "etf_count": len(etf_opportunities),
                    "crypto_count": len(crypto_opportunities),
                    "confidence_score": confidence_score,
                },
            )

            return collection

        except Exception as e:
            self.logger.error(f"Failed to extract A+ opportunities: {str(e)}", exc_info=True)
            return None

    def _extract_stock_opportunities(self) -> list[dict[str, any]]:
        """Extract A+ stock opportunities from a_plus_stocks.json file."""
        from finwiz.integration.opportunity_extractors import StockOpportunityExtractor

        stock_file = self.discovery_dir / "a_plus_stocks.json"

        # Load and parse JSON using helper method
        candidates = self._load_and_parse_json(stock_file, "stock")
        if not candidates:
            return []

        # Use stock extractor with Template Method pattern
        extractor = StockOpportunityExtractor()
        opportunities = extractor.extract(candidates)

        self.logger.info(f"Extracted {len(opportunities)} stock A+ opportunities")
        return opportunities

    def _extract_etf_opportunities(self) -> list[dict[str, any]]:
        """Extract A+ ETF opportunities from a_plus_etfs.json file."""
        from finwiz.integration.opportunity_extractors import ETFOpportunityExtractor

        etf_file = self.discovery_dir / "a_plus_etfs.json"

        # Load and parse JSON using helper method
        candidates = self._load_and_parse_json(etf_file, "etf")
        if not candidates:
            return []

        # Use ETF extractor with Template Method pattern
        extractor = ETFOpportunityExtractor()
        opportunities = extractor.extract(candidates)

        self.logger.info(f"Extracted {len(opportunities)} ETF A+ opportunities")
        return opportunities

    def _extract_crypto_opportunities(self) -> list[dict[str, any]]:
        """Extract A+ crypto opportunities from a_plus_crypto.json file."""
        from finwiz.integration.opportunity_extractors import CryptoOpportunityExtractor

        crypto_file = self.discovery_dir / "a_plus_crypto.json"

        # Load and parse JSON using helper method
        candidates = self._load_and_parse_json(crypto_file, "crypto")
        if not candidates:
            return []

        # Use crypto extractor with Template Method pattern
        extractor = CryptoOpportunityExtractor()
        opportunities = extractor.extract(candidates)

        self.logger.info(f"Extracted {len(opportunities)} crypto A+ opportunities")
        return opportunities

    def _generate_discovery_summary(self, stocks: list[dict], etfs: list[dict], cryptos: list[dict]) -> str:
        """Generate a summary of the discovery analysis."""
        total_opportunities = len(stocks) + len(etfs) + len(cryptos)

        if total_opportunities == 0:
            return "No A+ opportunities identified in current market conditions."

        summary_parts = []

        if stocks:
            a_plus_stocks = [s for s in stocks if s["grade"] == "A+"]
            summary_parts.append(f"{len(stocks)} stock opportunities identified ({len(a_plus_stocks)} A+ grade)")

        if etfs:
            a_plus_etfs = [e for e in etfs if e["grade"] == "A+"]
            summary_parts.append(f"{len(etfs)} ETF opportunities identified ({len(a_plus_etfs)} A+ grade)")

        if cryptos:
            a_plus_cryptos = [c for c in cryptos if c["grade"] == "A+"]
            summary_parts.append(f"{len(cryptos)} crypto opportunities identified ({len(a_plus_cryptos)} A+ grade)")

        summary = f"Discovery analysis identified {total_opportunities} high-quality investment opportunities: " + ", ".join(summary_parts)
        summary += ". Opportunities selected based on fundamental analysis, competitive moats, valuation attractiveness, and portfolio integration potential."

        return summary

    def _calculate_confidence_score(self, stocks: list[dict], etfs: list[dict], cryptos: list[dict]) -> float:
        """Calculate overall confidence score based on data availability and quality."""
        if not any([stocks, etfs, cryptos]):
            return 0.0

        # Base confidence on data availability
        base_confidence = 0.7

        # Boost confidence based on number of opportunities
        total_opportunities = len(stocks) + len(etfs) + len(cryptos)
        if total_opportunities >= 10:
            base_confidence += 0.2
        elif total_opportunities >= 5:
            base_confidence += 0.1

        # Boost confidence based on A+ grades
        a_plus_count = sum(
            [
                len([s for s in stocks if s["grade"] == "A+"]),
                len([e for e in etfs if e["grade"] == "A+"]),
                len([c for c in cryptos if c["grade"] == "A+"]),
            ]
        )

        if a_plus_count >= 5:
            base_confidence += 0.1
        elif a_plus_count >= 2:
            base_confidence += 0.05

        return min(base_confidence, 1.0)

    def _extract_allocation_recommendations(self, stocks: list[dict], etfs: list[dict], cryptos: list[dict]) -> list[dict]:
        """Extract allocation recommendations from all opportunities."""
        recommendations = []

        for idx, stock in enumerate(stocks, start=1):
            if stock.get("allocation_recommendation"):
                recommendations.append(
                    {
                        "asset_type": "stock",
                        "symbol": stock["symbol"],
                        "allocation": stock["allocation_recommendation"],
                        "grade": stock["grade"],
                        "rank": idx,
                    }
                )

        for idx, etf in enumerate(etfs, start=1):
            if etf.get("allocation_recommendation"):
                recommendations.append(
                    {
                        "asset_type": "etf",
                        "symbol": etf["symbol"],
                        "allocation": etf["allocation_recommendation"],
                        "grade": etf["grade"],
                        "rank": idx,
                    }
                )

        for idx, crypto in enumerate(cryptos, start=1):
            if crypto.get("allocation_recommendation"):
                recommendations.append(
                    {
                        "asset_type": "crypto",
                        "symbol": crypto["symbol"],
                        "allocation": crypto["allocation_recommendation"],
                        "grade": crypto["grade"],
                        "rank": idx,
                    }
                )

        return recommendations

    def _extract_replacement_notes(self, stocks: list[dict], etfs: list[dict], cryptos: list[dict]) -> list[str]:
        """Extract replacement notes from all opportunities."""
        notes = []

        for stock in stocks:
            if stock.get("replacement_note"):
                notes.append(f"{stock['symbol']}: {stock['replacement_note']}")

        for etf in etfs:
            if etf.get("replacement_note"):
                notes.append(f"{etf['symbol']}: {etf['replacement_note']}")

        for crypto in cryptos:
            if crypto.get("replacement_note"):
                notes.append(f"{crypto['symbol']}: {crypto['replacement_note']}")

        return notes

    def _extract_moat_info(self, moat_analysis: Any) -> tuple[str, str, list[str]]:
        """
        Extract moat information with guard clauses for different data types.

        Handles:
        - String type: Returns empty moat type/strength, uses string as rationale
        - Dict type: Extracts moat_type, moat_strength, builds rationale
        - Other types: Returns empty values

        Args:
            moat_analysis: Moat analysis data (string, dict, or other)

        Returns:
            Tuple of (moat_type, moat_strength, rationale_list)

        """
        # Guard: Handle None or empty
        if not moat_analysis:
            return "", "", []

        # Guard: Handle string type
        if isinstance(moat_analysis, str):
            return "", "", [moat_analysis]

        # Guard: Handle non-dict types
        if not isinstance(moat_analysis, dict):
            return "", "", []

        # Extract from dict
        moat_type = moat_analysis.get("moat_type", "")
        moat_strength = moat_analysis.get("moat_strength", "")
        rationale = [f"Moat: {moat_type}", f"Strength: {moat_strength}"] if moat_type else []

        return moat_type, moat_strength, rationale

    def _extract_diversification_info(self, diversification: Any) -> tuple[int, float, list[str]]:
        """
        Extract diversification information with guard clauses for different data types.

        Handles:
        - String type: Returns zero values, uses string as rationale
        - Dict type: Extracts holdings_count, top_10_concentration, builds rationale
        - Other types: Returns zero values

        Args:
            diversification: Diversification data (string, dict, or other)

        Returns:
            Tuple of (holdings_count, top_10_concentration, rationale_list)

        """
        # Guard: Handle None
        if diversification is None:
            return 0, 0.0, []

        # Guard: Handle string type
        if isinstance(diversification, str):
            # Empty string should return empty rationale
            if not diversification:
                return 0, 0.0, []
            return 0, 0.0, [diversification]

        # Guard: Handle non-dict types
        if not isinstance(diversification, dict):
            return 0, 0.0, []

        # Extract from dict (even if empty, return rationale with zero values)
        holdings_count = diversification.get("holdings_count", 0)
        top_10_concentration = diversification.get("top_10_concentration_pct", 0.0)
        rationale = [f"Holdings: {holdings_count}", f"Top 10 concentration: {top_10_concentration}%"]

        return holdings_count, top_10_concentration, rationale

    def _extract_technology_info(self, technology: Any) -> tuple[str, str, list[str]]:
        """
        Extract technology information with guard clauses for different data types.

        Handles:
        - String type: Returns empty values, uses string as rationale
        - Dict type: Extracts consensus_mechanism, use_case, builds rationale
        - Other types: Returns empty values

        Args:
            technology: Technology data (string, dict, or other)

        Returns:
            Tuple of (consensus_mechanism, use_case, rationale_list)

        """
        # Guard: Handle None or empty
        if not technology:
            return "", "", []

        # Guard: Handle string type
        if isinstance(technology, str):
            return "", "", [technology]

        # Guard: Handle non-dict types
        if not isinstance(technology, dict):
            return "", "", []

        # Extract from dict
        consensus = technology.get("consensus_mechanism", "")
        use_case = technology.get("primary_use_case", "")
        rationale = [f"Consensus: {consensus}", f"Use case: {use_case}"] if consensus else []

        return consensus, use_case, rationale

    def validate_aplus_opportunities(self, collection: APlusOpportunityCollection) -> tuple[bool, list[str]]:
        """
        Validate A+ opportunities collection for completeness and quality.

        Args:
            collection: The A+ opportunities collection to validate

        Returns:
            Tuple of (is_valid, list_of_validation_errors)

        """
        errors = []

        try:
            # Check if we have any opportunities
            total_opportunities = len(collection.etf_opportunities) + len(collection.stock_opportunities) + len(collection.crypto_opportunities)

            if total_opportunities == 0:
                errors.append("No A+ opportunities found in any asset class")

            # Check confidence score
            if collection.confidence_score < 0.5:
                errors.append(f"Low confidence score: {collection.confidence_score}")

            # Check discovery summary
            if len(collection.discovery_summary) < 50:
                errors.append("Discovery summary is too brief")

            # Check allocation recommendations
            if not collection.allocation_recommendations:
                errors.append("No allocation recommendations provided")

            # Check for duplicate symbols (extract symbols from APlusOpportunity objects)
            all_symbols = (
                [opp.symbol for opp in collection.stock_opportunities]
                + [opp.symbol for opp in collection.etf_opportunities]
                + [opp.symbol for opp in collection.crypto_opportunities]
            )

            if len(all_symbols) != len(set(all_symbols)):
                errors.append("Duplicate symbols found in opportunities")

            is_valid = len(errors) == 0

            self.logger.info(
                "A+ opportunities validation completed",
                extra={"is_valid": is_valid, "error_count": len(errors), "total_opportunities": total_opportunities},
            )

            return is_valid, errors

        except Exception as e:
            self.logger.error(f"A+ opportunities validation failed: {str(e)}", exc_info=True)
            return False, [f"Validation error: {str(e)}"]

    def _extract_market_context(self) -> dict[str, Any] | None:
        """Extract market context from discovery_latest.json."""
        try:
            discovery_file = self.discovery_dir / "discovery_latest.json"
            if not discovery_file.exists():
                return None

            content = discovery_file.read_text(encoding="utf-8")
            # Fix Python-style numeric literals
            content = self._clean_json_content(content)
            data = json.loads(content)

            # Extract market context if available
            market_context = data.get("market_context", {})
            if market_context:
                self.logger.info("Market context extracted from discovery results")
                return market_context

            return None
        except Exception as e:
            self.logger.warning(f"Could not extract market context: {e}")
            return None

    def _extract_backtesting_metrics(self) -> dict[str, Any] | None:
        """Extract backtesting metrics from discovery_latest.json."""
        try:
            discovery_file = self.discovery_dir / "discovery_latest.json"
            if not discovery_file.exists():
                return None

            content = discovery_file.read_text(encoding="utf-8")
            # Fix Python-style numeric literals
            content = self._clean_json_content(content)
            data = json.loads(content)

            # Extract validation results which contain backtesting data
            validation_results = data.get("validation_results", [])
            if validation_results:
                # Aggregate backtesting metrics
                metrics = {
                    "total_candidates_tested": len(validation_results),
                    "candidates_with_backtests": sum(1 for v in validation_results if v.get("backtest_results")),
                    "avg_sharpe_ratio": None,
                    "avg_annual_return": None,
                    "avg_max_drawdown": None,
                }

                # Calculate averages if backtest data exists
                sharpe_ratios = []
                annual_returns = []
                max_drawdowns = []

                for result in validation_results:
                    backtest = result.get("backtest_results", {})
                    if backtest:
                        if "sharpe_ratio" in backtest:
                            sharpe_ratios.append(backtest["sharpe_ratio"])
                        if "annual_return" in backtest:
                            annual_returns.append(backtest["annual_return"])
                        if "max_drawdown" in backtest:
                            max_drawdowns.append(backtest["max_drawdown"])

                if sharpe_ratios:
                    metrics["avg_sharpe_ratio"] = sum(sharpe_ratios) / len(sharpe_ratios)
                if annual_returns:
                    metrics["avg_annual_return"] = sum(annual_returns) / len(annual_returns)
                if max_drawdowns:
                    metrics["avg_max_drawdown"] = sum(max_drawdowns) / len(max_drawdowns)

                self.logger.info(f"Backtesting metrics extracted: {metrics['candidates_with_backtests']} candidates with backtests")
                return metrics

            return None
        except Exception as e:
            self.logger.warning(f"Could not extract backtesting metrics: {e}")
            return None
