"""
Portfolio Analysis Models.

Models for portfolio analysis, metrics, and performance tracking.
"""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field, field_validator

from .enums import RebalancingRecommendation


class PortfolioAnalysis(BaseModel):
    """Analysis of portfolio composition."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    total_value: float = Field(..., gt=0, description="Total portfolio value")
    weightings: dict[str, float] = Field(..., description="Current percentage weightings")
    deviations_from_target: dict[str, float] = Field(..., description="Deviations from target weights")
    positions_needing_rebalancing: list[str] = Field(default_factory=list, description="Symbols needing rebalancing")
    risk_metrics: dict[str, float] = Field(default_factory=dict, description="Portfolio risk metrics")

    @field_validator("weightings")
    @classmethod
    def validate_weightings_sum(cls, v: dict[str, float]) -> dict[str, float]:
        """Validate that weightings sum to approximately 1.0."""
        total = sum(v.values())
        if not (0.95 <= total <= 1.05):  # Allow some tolerance for rounding
            raise ValueError(f"Portfolio weightings sum to {total:.3f}, should be close to 1.0")
        return v


class RebalancingNeed(BaseModel):
    """Individual position rebalancing need assessment."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    symbol: str = Field(..., description="Symbol")
    current_weight: float = Field(..., ge=0, le=1, description="Current portfolio weight")
    target_weight: float = Field(..., ge=0, le=1, description="Target portfolio weight")
    deviation: float = Field(..., description="Deviation from target (positive = overweight)")
    tolerance_band: float = Field(..., gt=0, description="Tolerance band for this position")
    needs_rebalancing: bool = Field(..., description="Whether position needs rebalancing")
    urgency_score: float = Field(..., ge=0, le=1, description="Urgency score (0=low, 1=high)")


class PortfolioMetrics(BaseModel):
    """Portfolio-level metrics and statistics."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    # Basic portfolio composition
    total_value: float = Field(..., gt=0, description="Total portfolio value")
    number_of_positions: int = Field(..., ge=0, description="Number of positions in portfolio")
    largest_position_weight: float = Field(..., ge=0, le=1, description="Weight of largest position")

    # Risk metrics
    concentration_risk_score: float = Field(..., ge=0, le=10, description="Concentration risk score (0-10 scale)")
    diversification_ratio: float = Field(..., ge=0, description="Diversification ratio")
    effective_number_of_positions: float = Field(..., ge=0, description="Effective number of positions")

    # Rebalancing metrics
    turnover_if_rebalanced: float = Field(..., ge=0, le=1, description="Turnover required if rebalanced")
    cash_weight: float = Field(..., ge=0, le=1, description="Cash as percentage of portfolio")

    # Performance metrics (optional - may not always be available)
    total_return: float | None = Field(None, description="Total portfolio return")
    annualized_return: float | None = Field(None, description="Annualized return")
    volatility: float | None = Field(None, ge=0, description="Portfolio volatility")
    sharpe_ratio: float | None = Field(None, description="Sharpe ratio")
    max_drawdown: float | None = Field(None, le=0, description="Maximum drawdown")
    beta: float | None = Field(None, description="Portfolio beta vs benchmark")
    correlation_with_benchmark: float | None = Field(None, ge=-1, le=1, description="Correlation with benchmark")


class PerformanceAttribution(BaseModel):
    """Performance attribution analysis for rebalancing effectiveness."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    # Attribution periods
    attribution_start_date: datetime = Field(..., description="Start date for attribution analysis")
    attribution_end_date: datetime = Field(..., description="End date for attribution analysis")

    # Performance metrics
    total_return_with_rebalancing: float = Field(..., description="Total return with rebalancing")
    total_return_without_rebalancing: float = Field(..., description="Hypothetical return without rebalancing")
    rebalancing_alpha: float = Field(..., description="Alpha generated by rebalancing")

    # Cost-benefit analysis
    total_rebalancing_costs: float = Field(..., ge=0, description="Total costs incurred from rebalancing")
    net_benefit: float = Field(..., description="Net benefit after costs")
    cost_adjusted_alpha: float = Field(..., description="Alpha after adjusting for rebalancing costs")
    cost_drag: float = Field(..., ge=0, description="Cost drag from rebalancing as percentage of returns")

    # Risk metrics
    volatility_reduction: float = Field(..., description="Volatility reduction from rebalancing")
    tracking_error_vs_target: float = Field(..., ge=0, description="Tracking error vs target allocation")

    # Frequency analysis
    rebalancing_frequency_days: float = Field(..., gt=0, description="Average days between rebalancing")
    optimal_frequency_estimate: float = Field(..., gt=0, description="Estimated optimal rebalancing frequency")

    # Position-level attribution
    position_contributions: dict[str, float] = Field(default_factory=dict, description="Individual position contributions to alpha")


class TrendAnalysis(BaseModel):
    """Trend analysis for optimal rebalancing frequency identification."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    # Analysis parameters
    analysis_period_months: int = Field(..., gt=0, description="Analysis period in months")
    frequency_scenarios_tested: list[int] = Field(..., description="Rebalancing frequencies tested (in days)")

    # Results by frequency
    performance_by_frequency: dict[str, float] = Field(..., description="Performance results by rebalancing frequency")
    cost_by_frequency: dict[str, float] = Field(..., description="Cost results by rebalancing frequency")
    net_benefit_by_frequency: dict[str, float] = Field(..., description="Net benefit by rebalancing frequency")

    # Optimal frequency identification
    optimal_frequency_days: int = Field(..., gt=0, description="Identified optimal rebalancing frequency")
    confidence_in_optimal: float = Field(..., ge=0, le=1, description="Confidence in optimal frequency identification")

    # Market condition sensitivity
    performance_in_bull_markets: dict[str, float] = Field(default_factory=dict, description="Performance by frequency in bull markets")
    performance_in_bear_markets: dict[str, float] = Field(default_factory=dict, description="Performance by frequency in bear markets")


class RebalancingAnalytics(BaseModel):
    """Comprehensive analytics dashboard data."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    # Portfolio identification
    portfolio_id: str = Field(..., description="Portfolio identifier")

    # Current state
    current_portfolio_metrics: PortfolioMetrics = Field(..., description="Current portfolio metrics")
    current_rebalancing_needs: list[RebalancingNeed] = Field(..., description="Current rebalancing needs")

    # Historical performance
    performance_attribution: PerformanceAttribution | None = Field(None, description="Performance attribution analysis")
    trend_analysis: TrendAnalysis | None = Field(None, description="Trend analysis results")

    # Position histories
    position_histories: list = Field(default_factory=list, description="Historical tracking of individual positions")

    # Recommendations
    recommended_action: RebalancingRecommendation = Field(..., description="Overall recommended action")
    next_review_date: datetime = Field(..., description="Recommended next review date")
    strategy_recommendations: list[str] = Field(default_factory=list, description="Strategic recommendations for portfolio optimization")

    # Risk assessment
    portfolio_risk_score: float = Field(..., ge=0, le=10, description="Overall portfolio risk score (0=low, 10=high)")
    concentration_risk: float = Field(..., ge=0, le=1, description="Concentration risk measure")
    rebalancing_urgency: float = Field(..., ge=0, le=1, description="Urgency of rebalancing need")

    # Event tracking
    total_rebalancing_events: int = Field(default=0, ge=0, description="Total number of rebalancing events tracked")
