"""Strategic analysis schemas (PESTEL, SWOT, Porter's Five Forces).

Three independent qualitative frameworks generated by parallel AI agents
with Perplexity-grounded web research. Each framework self-rates its
``strategic_score`` and ``confidence`` so the composite strategic score is
pure averaging — no Python derivation from item counts.
"""

from typing import Literal

from pydantic import BaseModel, Field, field_validator


def _coerce_prose(v: object) -> str:
    """Coerce dict to pipe-joined string (AI sometimes returns dicts for prose)."""
    if isinstance(v, dict):
        return " | ".join(f"{k}: {val}" for k, val in v.items())
    return str(v) if v is not None else ""


def _coerce_str_list(v: object) -> list[str]:
    """Coerce a list whose entries may be dicts into a list of strings."""
    if not isinstance(v, list):
        return []
    out: list[str] = []
    for item in v:
        if isinstance(item, dict):
            label = item.get("name") or item.get("label") or item.get("description") or item.get("text") or str(item)
            severity = item.get("severity") or item.get("impact") or item.get("level")
            out.append(f"{label} (Sévérité: {severity})" if severity else str(label))
        else:
            out.append(str(item))
    return out


MAX_BULLETS_PESTEL = 3
MAX_BULLETS_SWOT = 4
MAX_BULLET_CHARS = 200
MAX_PROSE_CHARS = 400
MAX_RATIONALE_CHARS = 250


def _clamp_bullets(v: object, max_items: int) -> list[str]:
    """Trim a model's bullet list to the contract.

    Never raises: an over-long response is clamped, because rejecting it
    would cost the holding entirely.
    """
    items = _coerce_str_list(v)
    return [item[:MAX_BULLET_CHARS].rstrip() for item in items[:max_items]]


def _clamp_prose(v: object, max_chars: int) -> str:
    return _coerce_prose(v)[:max_chars].rstrip()


Intensity = Literal["LOW", "MEDIUM", "HIGH"]


class PestelAnalysis(BaseModel):
    """PESTEL macro-environmental analysis (Political/Economic/Social/Tech/Env/Legal)."""

    political: list[str] = Field(default_factory=list, description="Political factors: max 3 bullets")
    economic: list[str] = Field(default_factory=list, description="Economic factors: max 3 bullets")
    social: list[str] = Field(default_factory=list, description="Social factors: max 3 bullets")
    technological: list[str] = Field(default_factory=list, description="Technological factors: max 3 bullets")
    environmental: list[str] = Field(default_factory=list, description="Environmental factors: max 3 bullets")
    legal: list[str] = Field(default_factory=list, description="Legal factors: max 3 bullets")
    key_threats: list[str] = Field(default_factory=list, description="Most material PESTEL-derived threats")
    key_opportunities: list[str] = Field(default_factory=list, description="Most material PESTEL-derived opportunities")
    strategic_score: float = Field(default=0.5, ge=0.0, le=1.0, description="AI's overall PESTEL favorability (0=hostile, 1=very favorable)")
    confidence: float = Field(default=0.5, ge=0.0, le=1.0, description="AI's confidence in this assessment")

    @field_validator("political", "economic", "social", "technological", "environmental", "legal", mode="before")
    @classmethod
    def _clamp_dimension(cls, v: object) -> list[str]:
        return _clamp_bullets(v, MAX_BULLETS_PESTEL)

    @field_validator("key_threats", "key_opportunities", mode="before")
    @classmethod
    def _clamp_key_lists(cls, v: object) -> list[str]:
        return _clamp_bullets(v, MAX_BULLETS_PESTEL)

    model_config = {"str_strip_whitespace": True}


class SwotAnalysis(BaseModel):
    """SWOT analysis (Strengths/Weaknesses/Opportunities/Threats)."""

    strengths: list[str] = Field(default_factory=list, description="Internal strengths")
    weaknesses: list[str] = Field(default_factory=list, description="Internal weaknesses")
    opportunities: list[str] = Field(default_factory=list, description="External opportunities")
    threats: list[str] = Field(default_factory=list, description="External threats")
    strategic_assessment: str = Field(default="", description="AI's narrative summary tying SWOT together")
    strategic_score: float = Field(default=0.5, ge=0.0, le=1.0, description="AI's overall SWOT favorability (S+O vs W+T)")
    confidence: float = Field(default=0.5, ge=0.0, le=1.0, description="AI's confidence in this assessment")

    @field_validator("strengths", "weaknesses", "opportunities", "threats", mode="before")
    @classmethod
    def _clamp_lists(cls, v: object) -> list[str]:
        return _clamp_bullets(v, MAX_BULLETS_SWOT)

    @field_validator("strategic_assessment", mode="before")
    @classmethod
    def _clamp_assessment(cls, v: object) -> str:
        return _clamp_prose(v, MAX_PROSE_CHARS)

    model_config = {"str_strip_whitespace": True}


class ForceRating(BaseModel):
    """Single Porter force: intensity + rationale."""

    intensity: Intensity = Field(default="MEDIUM", description="LOW = favorable for the company, HIGH = unfavorable")
    rationale: str = Field(default="", description="Evidence-grounded rationale for the intensity rating")

    @field_validator("rationale", mode="before")
    @classmethod
    def _clamp_rationale(cls, v: object) -> str:
        return _clamp_prose(v, MAX_RATIONALE_CHARS)

    @field_validator("intensity", mode="before")
    @classmethod
    def _normalize_intensity(cls, v: object) -> str:
        if v is None:
            return "MEDIUM"
        s = str(v).strip().upper()
        if s in {"LOW", "FAIBLE", "L"}:
            return "LOW"
        if s in {"HIGH", "ÉLEVÉE", "ELEVEE", "H"}:
            return "HIGH"
        return "MEDIUM"

    model_config = {"str_strip_whitespace": True}


class FiveForcesAnalysis(BaseModel):
    """Porter's Five Forces competitive position analysis."""

    threat_of_new_entrants: ForceRating = Field(default_factory=ForceRating, description="Barriers to entry")
    bargaining_power_suppliers: ForceRating = Field(default_factory=ForceRating, description="Supplier leverage")
    bargaining_power_customers: ForceRating = Field(default_factory=ForceRating, description="Customer leverage")
    threat_of_substitutes: ForceRating = Field(default_factory=ForceRating, description="Substitute products/services")
    competitive_rivalry: ForceRating = Field(default_factory=ForceRating, description="Industry rivalry intensity")
    competitive_position_summary: str = Field(default="", description="AI's narrative on overall moat strength")
    strategic_score: float = Field(default=0.5, ge=0.0, le=1.0, description="AI's overall moat strength (1 = wide moat, 0 = no moat)")
    confidence: float = Field(default=0.5, ge=0.0, le=1.0, description="AI's confidence in this assessment")

    @field_validator("competitive_position_summary", mode="before")
    @classmethod
    def _clamp_summary(cls, v: object) -> str:
        return _clamp_prose(v, MAX_PROSE_CHARS)

    model_config = {"str_strip_whitespace": True}


class StrategicAnalysis(BaseModel):
    """Composite of the three independent strategic frameworks."""

    pestel: PestelAnalysis | None = Field(default=None, description="PESTEL macro analysis")
    swot: SwotAnalysis | None = Field(default=None, description="SWOT analysis")
    five_forces: FiveForcesAnalysis | None = Field(default=None, description="Porter's Five Forces analysis")

    model_config = {"str_strip_whitespace": True}

    @property
    def composite_strategic_score(self) -> float | None:
        """Average of the three framework scores. None if all three are missing."""
        scores = [f.strategic_score for f in (self.pestel, self.swot, self.five_forces) if f is not None]
        return sum(scores) / len(scores) if scores else None

    @property
    def composite_confidence(self) -> float | None:
        """Average of the three framework confidences. None if all three are missing."""
        confs = [f.confidence for f in (self.pestel, self.swot, self.five_forces) if f is not None]
        return sum(confs) / len(confs) if confs else None


class PortfolioStrategicPosture(BaseModel):
    """Portfolio-wide strategic synthesis (one per kickoff)."""

    macro_environment_summary: str = Field(default="", description="Cross-portfolio PESTEL synthesis (regulatory/economic/geopolitical themes)")
    portfolio_strengths: list[str] = Field(default_factory=list, description="Concentration of moats, structural advantages")
    portfolio_weaknesses: list[str] = Field(default_factory=list, description="Concentration risks, weak moats, exposure gaps")
    portfolio_opportunities: list[str] = Field(default_factory=list, description="Cross-cutting tailwinds the holdings can ride")
    portfolio_threats: list[str] = Field(default_factory=list, description="Systemic risks affecting multiple holdings")
    competitive_landscape_summary: str = Field(default="", description="Cross-holding Porter synthesis (industries with strongest/weakest moats)")
    dominant_themes: list[str] = Field(default_factory=list, description="Top 3-5 strategic themes recurring across the portfolio")
    overall_assessment: str = Field(default="", description="AI's narrative on the portfolio's strategic posture")
    strategic_score: float = Field(default=0.5, ge=0.0, le=1.0, description="AI's overall portfolio strategic favorability")
    confidence: float = Field(default=0.5, ge=0.0, le=1.0, description="AI's confidence in this synthesis")

    @field_validator("macro_environment_summary", "competitive_landscape_summary", "overall_assessment", mode="before")
    @classmethod
    def _coerce_prose_fields(cls, v: object) -> str:
        return _coerce_prose(v)

    @field_validator("portfolio_strengths", "portfolio_weaknesses", "portfolio_opportunities", "portfolio_threats", "dominant_themes", mode="before")
    @classmethod
    def _coerce_lists(cls, v: object) -> list[str]:
        return _coerce_str_list(v)

    model_config = {"str_strip_whitespace": True}
